name: build
on: [create, workflow_dispatch]

jobs:
  run:
    strategy:
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Repo setup
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: 'pypy3.9' 
      - name: Install deps
        run: pip install sympy tqdm
      - name: Run the script
        run: python src/main.py
      - name: Commit changes
        run: |
          git config --global user.email "fantomitechno@gmail.com"
          git config --global user.name "fantomitechno"
          git add .
          git commit -m ":D"
          git push origin scientist


